app:
  env: development
server:
  port: 8080
database:
  driver: sqlite
  dsn: file:./data/dev.db?cache=shared&_fk=1
redis:
  addr: 127.0.0.1:6379
logging:
  level: debug

bootstrap:
  enabled: true
  tenantID: dev-tenant
  tenantName: Development Tenant
  tenantDescription: Local development tenant
  adminEmail: admin
  adminPassword: admin123
  adminRole: admin
