app: # 应用层配置
  env: development # 强制运行环境为开发态
server: # HTTP 服务配置
  port: 8080 # 服务监听端口
  cors: # CORS 白名单配置
    allowOrigins: # 开发环境允许的前端来源
      - "*" # 默认放行全部来源，必要时改为具体域名
    allowCredentials: false # 是否允许附带认证信息
  securityHeaders: # 安全响应头配置
database: # 数据库配置
  driver: sqlite # 使用嵌入式 SQLite
  dsn: file:./data/dev.db?cache=shared&_fk=1 # SQLite 数据库文件路径
redis: # Redis 配置
  addr: 127.0.0.1:6379 # 本地 Redis 服务地址
logging: # 日志配置
  level: debug # 输出调试级日志
auth: # 认证与授权相关密钥
  accessTokenSecret: "k5tFvoo5sfW3jfykKCxkQ8g4S46kwyUF" # Access Token 签名密钥
  refreshTokenSecret: "k5tFvoo5sfW3jfykKCxkQ8g4S46kwyUF" # Refresh Token 签名密钥
  accessTokenTTL: 180m # Access Token 有效期
  refreshTokenTTL: 720h # Refresh Token 有效期
  apiKeyHashSecret: "k5tFvoo5sfW3jfykKCxkQ8g4S46kwyUF" # API Key 哈希盐值
  github: # GitHub OAuth 配置
    enabled: false # 默认为关闭，如需联调请切换为 true 并填写凭据
    clientId: "" # 本地调试用的 GitHub OAuth App Client ID
    clientSecret: "" # GitHub OAuth App Client Secret
    redirectUrl: "http://localhost:8080/api/v1/auth/github/callback" # 回调地址
    scopes:
      - read:user
      - user:email
    allowedOrgs: []
    stateTTL: 5m
seed: # 启动种子配置
  admin: # 本地初始管理员账号，可在此配置或通过环境变量覆盖
    email: "" # 默认空值，如需自动创建管理员请填写邮箱
    password: "" # 对应管理员密码，建议仅在开发环境使用
    role: admin # 指定角色，默认为 admin
